use std::collections::HashMap;
use std::env;
use std::fs;
use std::path::Path;
use serde::Deserialize;
use heck::AsSnakeCase;

#[derive(Debug, Deserialize)]
struct JsonBracket {
    upper_bound: Option<f64>,
    rate: f64,
}
type JsonTaxData = HashMap<String, HashMap<String, HashMap<String, Vec<JsonBracket>>>>;
type FilingStatusDeductions = HashMap<String, f64>;
type YearDeductions = HashMap<String, FilingStatusDeductions>;
type JsonDeductionsData = HashMap<String, YearDeductions>;


fn main() -> Result<(), Box<dyn std::error::Error>> {
    let cargo_manifest_dir = env::var("CARGO_MANIFEST_DIR")?;

    let tax_json_input_path = Path::new(&cargo_manifest_dir).join("src").join("Bracket.json"); 
    let generated_tax_output_path = Path::new(&cargo_manifest_dir).join("src").join("brackets.rs");

    println!("cargo:rerun-if-changed={}", tax_json_input_path.display());
    println!("cargo:rerun-if-changed=build.rs"); 
    eprintln!("DEBUG: build.rs started.");

    eprintln!("DEBUG: Reading tax brackets JSON from: {:?}", tax_json_input_path.display());
    let tax_json_content = fs::read_to_string(&tax_json_input_path)
        .map_err(|e| format!("Failed to read tax JSON from {}: {}", tax_json_input_path.display(), e))?;

    let parsed_tax_data: JsonTaxData = serde_json::from_str(&tax_json_content)
        .map_err(|e| format!("Failed to parse tax JSON from {}: {}", tax_json_input_path.display(), e))?;

    let mut tax_data_output = String::new();
    tax_data_output.push_str("// This file is automatically generated by build.rs\n");
    tax_data_output.push_str("// Do not edit this file directly. Changes will be overwritten.\n\n");
    tax_data_output.push_str("#[derive(Debug, Clone, Copy)]\n");
    tax_data_output.push_str("pub struct Bracket(pub f64, pub f64); // upper_boundary, tax_rate\n\n");

    for (state_code, state_data) in parsed_tax_data {
        for (year, year_data) in state_data {
            for (filing_status, brackets) in year_data {
                let snake_case_filing_status = AsSnakeCase(filing_status.as_str()).to_string();
                let func_name = format!("{}_{}_tax_{}",
                    state_code.to_lowercase(),
                    snake_case_filing_status,
                    year
                );

                tax_data_output.push_str(&format!("pub fn {}() -> Vec<Bracket> {{\n", func_name));
                tax_data_output.push_str("    vec![\n");

                for bracket in brackets {
                    let upper_bound_str = match bracket.upper_bound {
                        Some(val) => format!("{:.1}", val), 
                        None => "f64::INFINITY".to_string(),
                    };
                    tax_data_output.push_str(&format!("        Bracket({}, {:.1}),\n", upper_bound_str, bracket.rate));
                }
                tax_data_output.push_str("    ]\n");
                tax_data_output.push_str("}\n\n");
            }
        }
    }

    fs::write(&generated_tax_output_path, tax_data_output)
        .map_err(|e| format!("Failed to write to {}: {}", generated_tax_output_path.display(), e))?;
    eprintln!("DEBUG: Successfully wrote tax brackets code to: {:?}", generated_tax_output_path.display());


    // for deductions.json
    let deductions_json_input_path = Path::new(&cargo_manifest_dir).join("src").join("deductions.json");
    let generated_deductions_output_path = Path::new(&cargo_manifest_dir).join("src").join("deductions.rs");

    println!("cargo:rerun-if-changed={}", deductions_json_input_path.display());

    eprintln!("DEBUG: Reading deductions JSON from: {:?}", deductions_json_input_path.display());
    let deductions_json_content = fs::read_to_string(&deductions_json_input_path)
        .map_err(|e| format!("Failed to read deductions JSON from {}: {}", deductions_json_input_path.display(), e))?;

    let parsed_deductions_data: JsonDeductionsData = serde_json::from_str(&deductions_json_content)
        .map_err(|e| format!("Failed to parse deductions JSON from {}: {}", deductions_json_input_path.display(), e))?;

    let mut deductions_output = String::new();
    deductions_output.push_str("// This file is automatically generated by build.rs\n");
    deductions_output.push_str("// Do not edit this file directly. Changes will be overwritten.\n\n");
    deductions_output.push_str("use crate::FilingStatus;\n\n");
    deductions_output.push_str("use crate::Deduction;\n\n");


    for (state_code, state_data) in parsed_deductions_data {
        for (year, year_data) in state_data {
            for (filing_status,_amount) in year_data {
                let snake_case_filing_status = AsSnakeCase(filing_status.as_str()).to_string();
                let func_name = format!("{}_{}_deduction_{}",
                    state_code.to_lowercase(),
                    snake_case_filing_status,
                    year
                );
                deductions_output.push_str(&format!(
                    "pub fn {}(_income: f64, _filing_status_value: &FilingStatus) -> Deduction {{\n",
                    func_name
                ));
                deductions_output.push_str(&format!("    Deduction {{ standard_deduction: {:.1} }}\n}}\n", _amount));
            }
        }
    }

    fs::write(&generated_deductions_output_path, deductions_output)
        .map_err(|e| format!("Failed to write to {}: {}", generated_deductions_output_path.display(), e))?;
    eprintln!("DEBUG: Successfully wrote deductions code to: {:?}", generated_deductions_output_path.display());

    Ok(())
}