[package]
name = "tax_code"
version = "0.1.1"
edition = "2025"
description = "A code for calculating 2025 income tax"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Evie-lyn/tax_code/tree/master"
readme = "README.md"

[dependencies]
