use std::collections::HashMap;
use std::collections::HashSet;
use std::env;
use std::fs;
use std::path::Path;
use serde::Deserialize;
use heck::AsSnakeCase;

#[derive(Debug, Deserialize)]
struct JsonBracket {
    upper_bound: Option<f64>,
    rate: f64,
}
type JsonTaxData = HashMap<String, HashMap<String, HashMap<String, Vec<JsonBracket>>>>;

#[derive(Debug, Deserialize, Clone)] 
pub struct StepBracket {
    pub bracket_start: f64,
    pub bracket_end: f64,
    pub bracket_size: f64,
    pub deduction_start: f64,
    pub deduction_end: f64,
}

type JsonStepDeductionData = HashMap<String, HashMap<String, HashMap<String, StepBracket>>>; 

type FilingStatusDeductions = HashMap<String, f64>;
type YearDeductions = HashMap<String, FilingStatusDeductions>;
type JsonDeductionsData = HashMap<String, YearDeductions>; 

// For tax brackets
fn generate_tax_brackets ( cargo_manifest_dir: &Path,) -> Result<(), Box<dyn std::error::Error>> {
    let tax_json_input_path = cargo_manifest_dir.join("src").join("Bracket.json");
    let generated_tax_output_path = cargo_manifest_dir.join("src").join("brackets.rs");

    println!("cargo:rerun-if-changed={}", tax_json_input_path.display());

    eprintln!("DEBUG: Reading tax brackets JSON from: {:?}", tax_json_input_path.display());
    let tax_json_content = fs::read_to_string(&tax_json_input_path)
        .map_err(|e| format!("Failed to read tax JSON from {}: {}", tax_json_input_path.display(), e))?;

    let parsed_tax_data: JsonTaxData = serde_json::from_str(&tax_json_content)
        .map_err(|e| format!("Failed to parse tax JSON from {}: {}", tax_json_input_path.display(), e))?;

    let mut tax_data_output = String::new();
    tax_data_output.push_str("// This file is automatically generated by build.rs\n");
    tax_data_output.push_str("// Do not edit this file directly. Changes will be overwritten.\n\n");
    tax_data_output.push_str("#[derive(Debug, Clone, Copy)]\n");
    tax_data_output.push_str("pub struct Bracket(pub f64, pub f64); // upper_boundary, tax_rate\n\n");

    let mut sorted_states: Vec<&String> = parsed_tax_data.keys().collect();
    sorted_states.sort_unstable();

    for state_code in sorted_states {
        let state_data = parsed_tax_data.get(state_code).unwrap(); 

        let mut sorted_years: Vec<&String> = state_data.keys().collect();
        sorted_years.sort_unstable(); 

        for year in sorted_years {
            let year_data = state_data.get(year).unwrap(); 

            let mut sorted_filing_statuses: Vec<&String> = year_data.keys().collect();
            sorted_filing_statuses.sort_unstable();

            for filing_status in sorted_filing_statuses {
                let brackets = year_data.get(filing_status).unwrap(); 

                let snake_case_filing_status = AsSnakeCase(filing_status.as_str()).to_string();
                let func_name = format!("{}_{}_tax_{}",
                    state_code.to_lowercase(),
                    snake_case_filing_status,
                    year
                );

                tax_data_output.push_str(&format!("pub fn {}() -> Vec<Bracket> {{\n", func_name));
                tax_data_output.push_str("    vec![\n");

                for bracket in brackets {
                    let upper_bound_str = match bracket.upper_bound {
                        Some(val) => format!("{:.1}", val), 
                        None => "f64::INFINITY".to_string(),
                    };
                    tax_data_output.push_str(&format!("        Bracket({}, {:.1}),\n", upper_bound_str, bracket.rate));
                }
                tax_data_output.push_str("    ]\n");
                tax_data_output.push_str("}\n\n");
            }
        }
    }

    fs::write(&generated_tax_output_path, tax_data_output)
        .map_err(|e| format!("Failed to write to {}: {}", generated_tax_output_path.display(), e))?;
    eprintln!("DEBUG: Successfully wrote tax brackets code to: {:?}", generated_tax_output_path.display());

    Ok(())
}

fn generate_deductions (cargo_manifest_dir: &Path,) -> Result <(), Box<dyn std::error::Error>> {
    let deductions_json_input_path = cargo_manifest_dir.join("src").join("deductions.json");
    let generated_deductions_output_path = cargo_manifest_dir.join("src").join("deductions.rs");

    println!("cargo:rerun-if-changed={}", deductions_json_input_path.display());

    eprintln!("DEBUG: Reading deductions JSON from: {:?}", deductions_json_input_path.display());
    let deductions_json_content = fs::read_to_string(&deductions_json_input_path)
        .map_err(|e| format!("Failed to read deductions JSON from {}: {}", deductions_json_input_path.display(), e))?;

    let parsed_deductions_data: JsonDeductionsData = serde_json::from_str(&deductions_json_content)
        .map_err(|e| format!("Failed to parse deductions JSON from {}: {}", deductions_json_input_path.display(), e))?;

    let mut deductions_output = String::new();
    deductions_output.push_str("// This file is automatically generated by build.rs\n");
    deductions_output.push_str("// Do not edit this file directly. Changes will be overwritten.\n\n");
    deductions_output.push_str("use crate::FilingStatus;\n\n");
    deductions_output.push_str("use crate::Deduction;\n\n");


    let mut sorted_states: Vec<&String> = parsed_deductions_data.keys().collect();
    sorted_states.sort_unstable();

    for state_code in sorted_states {
        if state_code.to_lowercase() == "al" {
            continue; 
        }

        let state_data = parsed_deductions_data.get(state_code).unwrap();

        let mut sorted_years: Vec<&String> = state_data.keys().collect();
        sorted_years.sort_unstable_by_key(|y| y.parse::<i32>().unwrap_or_default());

        for year in sorted_years {
            let year_data = state_data.get(year).unwrap();

            let mut sorted_filing_statuses: Vec<&String> = year_data.keys().collect();
            sorted_filing_statuses.sort_unstable();

            for filing_status in sorted_filing_statuses {
                let amount = year_data.get(filing_status).unwrap();


                let snake_case_filing_status = AsSnakeCase(filing_status.as_str()).to_string();
                let func_name = format!("{}_{}_deduction_{}",
                    state_code.to_lowercase(),
                    snake_case_filing_status,
                    year
                );
                deductions_output.push_str(&format!(
                    "pub fn {}(_income: f64, _filing_status_value: &FilingStatus) -> Deduction {{\n",
                    func_name
                ));
                deductions_output.push_str(&format!("    Deduction {{ standard_deduction: {:.1} }}\n}}\n", amount));
            }
        }
    }

    fs::write(&generated_deductions_output_path, deductions_output)
        .map_err(|e| format!("Failed to write to {}: {}", generated_deductions_output_path.display(), e))?;
    eprintln!("DEBUG: Successfully wrote deductions code to: {:?}", generated_deductions_output_path.display());

    Ok(())
}

fn generate_get_tax_brackets(
    cargo_manifest_dir: &Path,
) -> Result<(), Box<dyn std::error::Error>> {
    let tax_json_input_path = cargo_manifest_dir.join("src").join("Bracket.json");
    let generated_get_tax_output_path = cargo_manifest_dir.join("src").join("get_tax_brackets.rs"); 

    println!("cargo:rerun-if-changed={}", tax_json_input_path.display());

    eprintln!("DEBUG: Reading tax brackets JSON for impl from: {:?}", tax_json_input_path.display());
    let tax_json_content = fs::read_to_string(&tax_json_input_path)
        .map_err(|e| format!("Failed to read tax JSON from {}: {}", tax_json_input_path.display(), e))?;

    let parsed_tax_data: JsonTaxData = serde_json::from_str(&tax_json_content)
        .map_err(|e| format!("Failed to parse tax JSON from {}: {}", tax_json_input_path.display(), e))?;

    let mut impl_output = String::new();
    impl_output.push_str("// This file is automatically generated by build.rs\n");
    impl_output.push_str("// Do not edit this file directly. Changes will be overwritten.\n\n");
    impl_output.push_str("use crate::FilingStatus;\n");
    impl_output.push_str("use crate::brackets::Bracket;\n"); 

    impl_output.push_str("/// Provides tax brackets for a given state, year, and filing status.\n");
    impl_output.push_str("/// This function is generated by build.rs.\n");
    impl_output.push_str("pub fn get_tax_brackets(state: &str, year: i32, filing_status: &FilingStatus) -> Vec<Bracket> {\n");
    impl_output.push_str("    let state_lower = state.to_lowercase();\n");
    impl_output.push_str("    match state_lower.as_str() {\n");

    let mut sorted_states: Vec<&String> = parsed_tax_data.keys().collect();
    sorted_states.sort_unstable();

    for state_code in sorted_states { 
        let state_data = parsed_tax_data.get(state_code).unwrap();
        impl_output.push_str(&format!("        \"{}\" => match year {{\n", state_code.to_lowercase()));

        let mut years_in_state_str: Vec<&String> = state_data.keys().collect();
        years_in_state_str.sort_unstable_by_key(|y| y.parse::<i32>().unwrap_or_default()); 

        let latest_year = years_in_state_str.last().map(|s| s.parse::<i32>().unwrap_or_default());

        for year_str in years_in_state_str { 
            let year = year_str.parse::<i32>().unwrap(); 
            let year_data = state_data.get(year_str).unwrap();
            impl_output.push_str(&format!("            {} => match filing_status {{\n", year));

            let mut sorted_filing_statuses: Vec<&String> = year_data.keys().collect();
            sorted_filing_statuses.sort_unstable();

            for filing_status in sorted_filing_statuses { 
                let brackets = year_data.get(filing_status).unwrap();
                let filing_status_variant = format!("FilingStatus::{}", filing_status);

                impl_output.push_str(&format!(
                    "                {} => vec![\n",
                    filing_status_variant
                ));

                for bracket in brackets {
                    let upper_bound_str = match bracket.upper_bound {
                        Some(val) => format!("{:.1}", val),
                        None => "f64::INFINITY".to_string(),
                    };
                    impl_output.push_str(&format!("                    Bracket({}, {:.4}),\n", upper_bound_str, bracket.rate));
                }
                impl_output.push_str("                ],\n"); 
            }
            impl_output.push_str("            },\n"); 
        }

        if let Some(latest_year_val) = latest_year {
            impl_output.push_str(&format!(
                "            _ => {{\n                eprintln!(\"Year {{}} not supported for {}. Defaulting to {} Single bracket.\", year);\n",
                state_code.to_lowercase(), latest_year_val
            ));
            if let Some(latest_year_data) = parsed_tax_data.get(state_code).and_then(|s_data| s_data.get(&latest_year_val.to_string())) {
                if let Some(single_brackets) = latest_year_data.get("Single") {
                    impl_output.push_str("                vec![\n");
                    for bracket in single_brackets {
                        let upper_bound_str = match bracket.upper_bound {
                            Some(val) => format!("{:.1}", val),
                            None => "f64::INFINITY".to_string(),
                        };
                        impl_output.push_str(&format!("                    Bracket({}, {:.1}),\n", upper_bound_str, bracket.rate));
                    }
                    impl_output.push_str("                ]\n");
                } else {
                    impl_output.push_str("                vec![Bracket(f64::INFINITY, 0.0)]\n");
                }
            } else {
                impl_output.push_str("                vec![Bracket(f64::INFINITY, 0.0)]\n");
            }
            impl_output.push_str("            }\n"); 
        } else {
            impl_output.push_str("            _ => {\n");
            impl_output.push_str("                eprintln!(\"No year data found for {}. Defaulting to empty brackets.\", state);\n");
            impl_output.push_str("                vec![Bracket(f64::INFINITY, 0.0)]\n");
            impl_output.push_str("            }\n");
        }


        impl_output.push_str("        },\n"); 
    }

    impl_output.push_str("        _ => {\n");
    impl_output.push_str("            eprintln!(\"Error: State '{}' is not currently supported.\", state);\n");
    impl_output.push_str("            vec![Bracket(f64::INFINITY, 0.0)]\n");
    impl_output.push_str("        }\n");
    impl_output.push_str("    }\n"); 
    impl_output.push_str("}\n"); 

    fs::write(&generated_get_tax_output_path, impl_output)
        .map_err(|e| format!("Failed to write to {}: {}", generated_get_tax_output_path.display(), e))?;
    eprintln!("DEBUG: Successfully wrote get_tax_brackets implementation to: {:?}", generated_get_tax_output_path.display());

    Ok(())
}

fn generate_get_deductions(
    cargo_manifest_dir: &Path,
) -> Result<(), Box<dyn std::error::Error>> {
    let deductions_json_input_path = cargo_manifest_dir.join("src").join("deductions.json");
    let generated_get_deductions_output_path = cargo_manifest_dir.join("src").join("get_deductions.rs");

    println!("cargo:rerun-if-changed={}", deductions_json_input_path.display());
    println!("cargo:rerun-if-changed={}", cargo_manifest_dir.join("src").join("step_deduction.json").display());

    eprintln!("DEBUG: Reading deductions JSON for impl from: {:?}", deductions_json_input_path.display());
    let deductions_json_content = fs::read_to_string(&deductions_json_input_path)
        .map_err(|e| format!("Failed to read deductions JSON from {}: {}", deductions_json_input_path.display(), e))?;

    let parsed_deductions_data: JsonDeductionsData = serde_json::from_str(&deductions_json_content)
        .map_err(|e| format!("Failed to parse deductions JSON from {}: {}", deductions_json_input_path.display(), e))?;

    let step_deduction_json_path = cargo_manifest_dir.join("src").join("step_deduction.json");
    let step_json_content = fs::read_to_string(&step_deduction_json_path)
        .map_err(|e| format!("Failed to read step deductions JSON from {}: {}", step_deduction_json_path.display(), e))?;
    let parsed_step_data: JsonStepDeductionData = serde_json::from_str(&step_json_content)
        .map_err(|e| format!("Failed to parse step deductions JSON from {}: {}", step_deduction_json_path.display(), e))?;

    let mut impl_output = String::new();
    impl_output.push_str("// This file is automatically generated by build.rs\n");
    impl_output.push_str("// Do not edit this file directly. Changes will be overwritten.\n\n");
    impl_output.push_str("use crate::FilingStatus;\n");
    impl_output.push_str("use crate::Deduction;\n");
    impl_output.push_str("use crate::income_based_deduction;\n\n"); 

    impl_output.push_str("/// Provides standard deductions for a given state, year, and filing status.\n");
    impl_output.push_str("/// This function is generated by build.rs.\n");
    impl_output.push_str("pub fn get_deductions(state: &str, year: i32, filing_status: &FilingStatus, income: f64) -> Deduction {\n");
    impl_output.push_str("    let state_lower = state.to_lowercase();\n");
    impl_output.push_str("    match state_lower.as_str() {\n");
   
    let mut unique_states: HashSet<String> = HashSet::new();
    for state_code in parsed_deductions_data.keys() {
        unique_states.insert(state_code.to_lowercase());
    }
    let mut states_with_step_deductions: HashSet<String> = HashSet::new();
    // Add states with step deductions
    for state_code in parsed_step_data.keys() {
        unique_states.insert(state_code.to_lowercase());
        states_with_step_deductions.insert(state_code.to_lowercase());
    }



    let mut all_states: Vec<String> = unique_states.into_iter().collect();
    all_states.sort_unstable(); 

    for state_code in &all_states {
        impl_output.push_str(&format!("        \"{}\" => match year {{\n", state_code));

        if states_with_step_deductions.contains(state_code) { 
            let data = parsed_step_data.get(state_code.to_uppercase().as_str()).expect(&format!("State '{}' data not found in step_deduction.json but was expected. Ensure '{}' key exists at the top level.", state_code, state_code));
            let mut years_to_process: Vec<&String> = data.keys().collect();
            years_to_process.sort_unstable_by_key(|y| y.parse::<i32>().unwrap_or_default());

            let latest_year = years_to_process.last().map(|s| s.parse::<i32>().unwrap_or_default());

            for year_str in years_to_process {
                let year = year_str.parse::<i32>().unwrap();
                let func_name = format!("income_based_deduction::{}_standard_deduction_{}", state_code, year);
                impl_output.push_str(&format!("            {} => {}(income, filing_status),\n", year, func_name));
            }

            if let Some(latest_year_val) = latest_year {
                impl_output.push_str(&format!(
                    "            _ => {{\n                eprintln!(\"Year {{}} not supported for {{}}. Defaulting to latest ({{}}) deduction.\", year, state_lower, {});\n",
                    latest_year_val
                ));
                let func_name = format!("income_based_deduction::{}_standard_deduction_{}", state_code, latest_year_val);
                impl_output.push_str(&format!("                {}(income, filing_status)\n", func_name));
                impl_output.push_str("            }\n"); 
            } else {
                impl_output.push_str(&format!("            _ => {{\n                eprintln!(\"No specific years found for {}. Defaulting to 0 deduction.\");\n", state_code));                impl_output.push_str("                Deduction { standard_deduction: 0.0 }\n");
                impl_output.push_str("            }\n");
            }
            impl_output.push_str("        },\n"); 
        } else {
            let state_data = parsed_deductions_data.get(&state_code.to_uppercase()).expect(&format!("State '{}' not found in deductions.json but was expected.", state_code));
            
            let mut years_in_state_str: Vec<&String> = state_data.keys().collect();
            years_in_state_str.sort_unstable_by_key(|y| y.parse::<i32>().unwrap_or_default());

            let latest_year = years_in_state_str.last().map(|s| s.parse::<i32>().unwrap_or_default());

            for year_str in years_in_state_str {
                let year = year_str.parse::<i32>().unwrap();
                let year_data = state_data.get(year_str).unwrap();
                impl_output.push_str(&format!("            {} => match *filing_status {{\n", year));

                let mut sorted_filing_statuses: Vec<&String> = year_data.keys().collect();
                sorted_filing_statuses.sort_unstable();

                for filing_status in sorted_filing_statuses {
                    let amount = year_data.get(filing_status).unwrap(); 
                    let filing_status_variant = format!("FilingStatus::{}", filing_status);
                    impl_output.push_str(&format!(
                        "                {} => Deduction {{ standard_deduction: {:.1} }},\n", 
                        filing_status_variant,
                        amount 
                    ));
                }
                impl_output.push_str("            }\n"); 
            }

            if let Some(latest_year_val) = latest_year {
                impl_output.push_str(&format!(
                    "            _ => {{\n                eprintln!(\"Year {{}} not supported for {{}}. Defaulting to standard deduction for Single filing status.\", year, state_lower);\n"
                ));
                if let Some(latest_year_data) = parsed_deductions_data.get(&state_code.to_uppercase()).and_then(|s_data| s_data.get(&latest_year_val.to_string())) {
                    if let Some(&single_deduction_amount) = latest_year_data.get("Single") {
                        impl_output.push_str(&format!("                Deduction {{ standard_deduction: {:.1} }}\n", single_deduction_amount));
                    } else {
                        impl_output.push_str("                Deduction { standard_deduction: 0.0 }\n");
                    }
                } else {
                    impl_output.push_str("                Deduction { standard_deduction: 0.0 }\n");
                }
                impl_output.push_str("            }\n");
            } else {
                impl_output.push_str(&format!("            _ => {{\n                eprintln!(\"No year data found for {{}}. Defaulting to 0 deduction.\", state_lower);\n", ));                impl_output.push_str("                Deduction { standard_deduction: 0.0 }\n");
                impl_output.push_str("            }\n");
            }
            impl_output.push_str("        },\n"); 
        }
    }

    impl_output.push_str("        _ => {\n");
    impl_output.push_str("            eprintln!(\"Error: State '{}' is not currently supported for deductions. Defaulting to 0 deduction.\", state);\n");
    impl_output.push_str("            Deduction { standard_deduction: 0.0 }\n");
    impl_output.push_str("        }\n");
    impl_output.push_str("    }\n"); 
    impl_output.push_str("}\n");

    fs::write(&generated_get_deductions_output_path, impl_output)
        .map_err(|e| format!("Failed to write to {}: {}", generated_get_deductions_output_path.display(), e))?;
    eprintln!("DEBUG: Successfully wrote get_deductions implementation to: {:?}", generated_get_deductions_output_path.display());

    Ok(())
}

fn generate_get_taxable_social_security(
    cargo_manifest_dir: &Path,
) -> Result<(), Box<dyn std::error::Error>> {
    use serde_json::Value;

    let state_ss_json_path = cargo_manifest_dir.join("src").join("social_security_taxes.json");
    let federal_ss_json_path = cargo_manifest_dir.join("src").join("taxable_social_security.json");
    let generated_output_path = cargo_manifest_dir.join("src").join("get_taxable_social_security.rs");

    println!("cargo:rerun-if-changed={}", state_ss_json_path.display());
    println!("cargo:rerun-if-changed={}", federal_ss_json_path.display());

    eprintln!(
        "DEBUG: Reading social security JSONs from: {:?} and {:?}",
        state_ss_json_path.display(),
        federal_ss_json_path.display()
    );

    let state_ss_content = fs::read_to_string(&state_ss_json_path)
        .map_err(|e| format!("Failed to read social security JSON from {}: {}", state_ss_json_path.display(), e))?;
    let federal_ss_content = fs::read_to_string(&federal_ss_json_path)
        .map_err(|e| format!("Failed to read federal social security JSON from {}: {}", federal_ss_json_path.display(), e))?;

    let state_ss_json: Value = serde_json::from_str(&state_ss_content)
        .map_err(|e| format!("Failed to parse social security JSON from {}: {}", state_ss_json_path.display(), e))?;
    let federal_ss_json: Value = serde_json::from_str(&federal_ss_content)
        .map_err(|e| format!("Failed to parse federal social security JSON from {}: {}", federal_ss_json_path.display(), e))?;

    let mut output = String::new();
    output.push_str("// This file is automatically generated by build.rs\n");
    output.push_str("// Do not edit this file directly. Changes will be overwritten.\n\n");
    output.push_str("use crate::FilingStatus;\n\n");

    // Helper to compute federal rate based on income brackets for the filing status
    output.push_str("fn federal_rate(year: i32, filing_status: &FilingStatus, income: f64) -> f64 {\n");
    output.push_str("    match year {\n");

    if let Value::Object(years) = &federal_ss_json {
        let mut year_keys: Vec<i32> = years.keys().filter_map(|k| k.parse::<i32>().ok()).collect();
        year_keys.sort_unstable();
        for year in year_keys {
            let year_key = year.to_string();
            if let Some(Value::Object(fs_map)) = years.get(&year_key) {
                output.push_str(&format!("        {} => match filing_status {{\n", year));
                let mut filing_keys: Vec<&String> = fs_map.keys().collect();
                filing_keys.sort_unstable();
                for fs_name in filing_keys {
                    if let Some(Value::Array(brackets)) = fs_map.get(fs_name.as_str()) {
                        output.push_str(&format!("            FilingStatus::{} => {{\n", fs_name));
                        output.push_str("                let mut rate: f64 = 0.0;\n");
                        // Build a proper if/else-if/else chain
                        let len = brackets.len();
                        let mut idx = 0usize;
                        for b in brackets {
                            idx += 1;
                            if let Value::Object(b_obj) = b {
                                let rate_v = b_obj.get("rate").and_then(|v| v.as_f64()).unwrap_or(0.0);
                                let ub_is_inf = matches!(b_obj.get("upper_bound"), Some(Value::Null) | None);
                                let ub_v = match b_obj.get("upper_bound") {
                                    Some(Value::Number(n)) => n.as_f64().unwrap_or(f64::INFINITY),
                                    _ => f64::INFINITY,
                                };
                                if ub_is_inf || idx == len {
                                    if len == 1 {
                                        output.push_str(&format!("                rate = {:.4};\n", rate_v));
                                    } else {
                                        output.push_str(&format!("                else {{ rate = {:.4}; }}\n", rate_v));
                                    }
                                } else {
                                    if idx == 1 {
                                        output.push_str(&format!("                if income <= {:.1} {{ rate = {:.4}; }}\n", ub_v, rate_v));
                                    } else {
                                        output.push_str(&format!("                else if income <= {:.1} {{ rate = {:.4}; }}\n", ub_v, rate_v));
                                    }
                                }
                            }
                        }
                        output.push_str("                rate\n");
                        output.push_str("            }\n");
                    }
                }
                // Wildcard: fallback to Single brackets if available, otherwise MarriedFilingJointly, else default 0.85
                if let Some(Value::Array(single_brackets)) = fs_map.get("Single") {
                    output.push_str("            _ => {\n");
                    output.push_str("                let mut rate: f64 = 0.0;\n");
                    let len = single_brackets.len();
                    let mut idx = 0usize;
                    for b in single_brackets {
                        idx += 1;
                        if let Value::Object(b_obj) = b {
                            let rate_v = b_obj.get("rate").and_then(|v| v.as_f64()).unwrap_or(0.0);
                            let ub_is_inf = matches!(b_obj.get("upper_bound"), Some(Value::Null) | None);
                            let ub_v = match b_obj.get("upper_bound") {
                                Some(Value::Number(n)) => n.as_f64().unwrap_or(f64::INFINITY),
                                _ => f64::INFINITY,
                            };
                            if ub_is_inf || idx == len {
                                if len == 1 {
                                    output.push_str(&format!("                rate = {:.4};\n", rate_v));
                                } else {
                                    output.push_str(&format!("                else {{ rate = {:.4}; }}\n", rate_v));
                                }
                            } else {
                                if idx == 1 {
                                    output.push_str(&format!("                if income <= {:.1} {{ rate = {:.4}; }}\n", ub_v, rate_v));
                                } else {
                                    output.push_str(&format!("                else if income <= {:.1} {{ rate = {:.4}; }}\n", ub_v, rate_v));
                                }
                            }
                        }
                    }
                    output.push_str("                rate\n");
                    output.push_str("            },\n");
                } else if let Some(Value::Array(mfj_brackets)) = fs_map.get("MarriedFilingJointly") {
                    output.push_str("            _ => {\n");
                    output.push_str("                let mut rate: f64 = 0.0;\n");
                    let len = mfj_brackets.len();
                    let mut idx = 0usize;
                    for b in mfj_brackets {
                        idx += 1;
                        if let Value::Object(b_obj) = b {
                            let rate_v = b_obj.get("rate").and_then(|v| v.as_f64()).unwrap_or(0.0);
                            let ub_is_inf = matches!(b_obj.get("upper_bound"), Some(Value::Null) | None);
                            let ub_v = match b_obj.get("upper_bound") {
                                Some(Value::Number(n)) => n.as_f64().unwrap_or(f64::INFINITY),
                                _ => f64::INFINITY,
                            };
                            if ub_is_inf || idx == len {
                                if len == 1 {
                                    output.push_str(&format!("                rate = {:.4};\n", rate_v));
                                } else {
                                    output.push_str(&format!("                else {{ rate = {:.4}; }}\n", rate_v));
                                }
                            } else {
                                if idx == 1 {
                                    output.push_str(&format!("                if income <= {:.1} {{ rate = {:.4}; }}\n", ub_v, rate_v));
                                } else {
                                    output.push_str(&format!("                else if income <= {:.1} {{ rate = {:.4}; }}\n", ub_v, rate_v));
                                }
                            }
                        }
                    }
                    output.push_str("                rate\n");
                    output.push_str("            },\n");
                } else {
                    output.push_str("            _ => { 0.85 },\n");
                }
                output.push_str("        },\n");
            }
        }
        output.push_str("        _ => { 0.85 }\n");
    } else {
        output.push_str("        _ => { 0.85 }\n");
    }
    output.push_str("    }\n}\n\n");

    // Main entry
    output.push_str("/// Returns the amount of Social Security income that is subject to tax for a given state/year.\n");
    output.push_str("pub fn get_taxable_social_security(state: &str, year: i32, age: i32, filing_status: &FilingStatus, income: f64, social_security_income: f64) -> f64 {\n");
    output.push_str("    let state_lower = state.to_lowercase();\n");
    output.push_str("    match state_lower.as_str() {\n");

    if let Value::Object(states) = &state_ss_json {
        let mut state_codes: Vec<&String> = states.keys().collect();
        state_codes.sort_unstable();
        for state_code in state_codes {
            output.push_str(&format!("        \"{}\" => match year {{\n", state_code.to_lowercase()));
            if let Some(Value::Object(years)) = states.get(state_code) {
                let mut year_keys: Vec<i32> = years.keys().filter_map(|k| k.parse::<i32>().ok()).collect();
                year_keys.sort_unstable();
                let latest_year = year_keys.last().cloned();

                for y in &year_keys {
                    let y_str = y.to_string();
                    if let Some(year_val) = years.get(&y_str) {
                        output.push_str(&format!("            {} => {{\n", y));
                        if let Value::Object(fs_or_age_map) = year_val {
                            let is_direct_fs = fs_or_age_map.keys().any(|k| k == "Single" || k == "MarriedFilingJointly" || k == "MarriedFilingSeparately" || k == "HeadOfHousehold" || k == "QualifyingSurvivingSpouse");
                            if is_direct_fs {
                                output.push_str("                match filing_status {\n");
                                let mut fs_keys: Vec<&String> = fs_or_age_map.keys().collect();
                                fs_keys.sort_unstable();
                                for fs_name in fs_keys {
                                    let val = fs_or_age_map.get(fs_name.as_str()).unwrap();
                                    match val {
                                        Value::String(s) if s == "federal" => {
                                            output.push_str(&format!("                    FilingStatus::{} => social_security_income * federal_rate({}, filing_status, income),\n", fs_name, y));
                                        }
                                        Value::Array(brackets) => {
                                            output.push_str(&format!("                    FilingStatus::{} => {{\n", fs_name));
                                            output.push_str("                        let mut rate: f64 = 0.0;\n");
                                            output.push_str("                        let mut deduction: f64 = 0.0;\n");
                                            let len = brackets.len();
                                            let mut idx = 0usize;
                                            for b in brackets {
                                                idx += 1;
                                                if let Value::Object(b_obj) = b {
                                                    let rate_v = b_obj.get("rate").and_then(|v| v.as_f64()).unwrap_or(0.0);
                                                    let ub_is_inf = matches!(b_obj.get("upper_bound"), Some(Value::Null) | None);
                                                    let ub_v = match b_obj.get("upper_bound") {
                                                        Some(Value::Number(n)) => n.as_f64().unwrap_or(f64::INFINITY),
                                                        _ => f64::INFINITY,
                                                    };
                                                    let ded_v = b_obj.get("deduction").and_then(|v| v.as_f64()).unwrap_or(0.0);
                                                    if ub_is_inf || idx == len {
                                                        if len == 1 {
                                                            output.push_str(&format!("                        rate = {:.4}; deduction = {:.1};\n", rate_v, ded_v));
                                                        } else {
                                                            output.push_str(&format!("                        else {{ rate = {:.4}; deduction = {:.1}; }}\n", rate_v, ded_v));
                                                        }
                                                    } else {
                                                        if idx == 1 {
                                                            output.push_str(&format!("                        if income <= {:.1} {{ rate = {:.4}; deduction = {:.1}; }}\n", ub_v, rate_v, ded_v));
                                                        } else {
                                                            output.push_str(&format!("                        else if income <= {:.1} {{ rate = {:.4}; deduction = {:.1}; }}\n", ub_v, rate_v, ded_v));
                                                        }
                                                    }
                                                }
                                            }
                                            output.push_str("                        let taxable_base = (social_security_income - deduction).max(0.0);\n");
                                            output.push_str("                        taxable_base * rate\n");
                                            output.push_str("                    }\n");
                                        }
                                        _ => {}
                                    }
                                }
                                // Add wildcard fallback: prefer Single if present at this year, else MarriedFilingJointly, else federal Single
                                let has_single = fs_or_age_map.get("Single").is_some();
                                let has_mfj = fs_or_age_map.get("MarriedFilingJointly").is_some();
                                if has_single {
                                    output.push_str(&format!("                    _ => return get_taxable_social_security(state, {}, age, &FilingStatus::Single, income, social_security_income),\n", y));
                                } else if has_mfj {
                                    output.push_str(&format!("                    _ => return get_taxable_social_security(state, {}, age, &FilingStatus::MarriedFilingJointly, income, social_security_income),\n", y));
                                } else {
                                    output.push_str(&format!("                    _ => return social_security_income * federal_rate({}, &FilingStatus::Single, income),\n", y));
                                }
                                output.push_str("                }\n");
                            } else {
                                // Age-tiered map
                                let mut age_keys: Vec<i32> = fs_or_age_map.keys().filter_map(|k| k.parse::<i32>().ok()).collect();
                                age_keys.sort_unstable();
                                if !age_keys.is_empty() {
                                    let min_age = age_keys[0];
                                    let max_age = *age_keys.last().unwrap();
                                    output.push_str(&format!("                let chosen_age = if age <= {} {{ {} }} else {{\n", min_age, min_age));
                                    for w in 1..age_keys.len() {
                                        output.push_str(&format!("                    if age <= {} {{ {} }} else {{\n", age_keys[w], age_keys[w]));
                                    }
                                    output.push_str(&format!("                        {}", max_age));
                                    for _ in 1..=age_keys.len() { output.push_str(" } "); }
                                    output.push_str(";\n");

                                    output.push_str("                match chosen_age {\n");
                                    for a in &age_keys {
                                        let a_str = a.to_string();
                                        if let Some(age_val) = fs_or_age_map.get(&a_str) {
                                            let mut fs_to_brackets: Vec<(String, Vec<Value>)> = Vec::new();
                                            match age_val {
                                                Value::Object(fsmap) => {
                                                    for (fs_name, v) in fsmap {
                                                        if let Value::Array(arr) = v { fs_to_brackets.push((fs_name.clone(), arr.clone())); }
                                                    }
                                                }
                                                Value::Array(items) => {
                                                    for item in items {
                                                        if let Value::Object(fsmap) = item {
                                                            for (fs_name, v) in fsmap {
                                                                if let Value::Array(arr) = v { fs_to_brackets.push((fs_name.clone(), arr.clone())); }
                                                            }
                                                        }
                                                    }
                                                }
                                                _ => {}
                                            }

                                            output.push_str(&format!("                    {} => match filing_status {{\n", a));
                                            fs_to_brackets.sort_by(|a, b| a.0.cmp(&b.0));
                                            for (fs_name, brackets) in fs_to_brackets {
                                                output.push_str(&format!("                        FilingStatus::{} => {{\n", fs_name));
                                                output.push_str("                            let mut rate: f64 = 0.0;\n");
                                                output.push_str("                            let mut deduction: f64 = 0.0;\n");
                                                let len = brackets.len();
                                                let mut idx = 0usize;
                                                for b in brackets {
                                                    idx += 1;
                                                    if let Value::Object(b_obj) = b {
                                                        let rate_v = b_obj.get("rate").and_then(|v| v.as_f64()).unwrap_or(0.0);
                                                        let ub_is_inf = matches!(b_obj.get("upper_bound"), Some(Value::Null) | None);
                                                        let ub_v = match b_obj.get("upper_bound") {
                                                            Some(Value::Number(n)) => n.as_f64().unwrap_or(f64::INFINITY),
                                                            _ => f64::INFINITY,
                                                        };
                                                        let ded_v = b_obj.get("deduction").and_then(|v| v.as_f64()).unwrap_or(0.0);
                                                        if ub_is_inf || idx == len {
                                                            if len == 1 {
                                                                output.push_str(&format!("                            rate = {:.4}; deduction = {:.1};\n", rate_v, ded_v));
                                                            } else {
                                                                output.push_str(&format!("                            else {{ rate = {:.4}; deduction = {:.1}; }}\n", rate_v, ded_v));
                                                            }
                                                        } else {
                                                            if idx == 1 {
                                                                output.push_str(&format!("                            if income <= {:.1} {{ rate = {:.4}; deduction = {:.1}; }}\n", ub_v, rate_v, ded_v));
                                                            } else {
                                                                output.push_str(&format!("                            else if income <= {:.1} {{ rate = {:.4}; deduction = {:.1}; }}\n", ub_v, rate_v, ded_v));
                                                            }
                                                        }
                                                    }
                                                }
                                                output.push_str("                            let taxable_base = (social_security_income - deduction).max(0.0);\n");
                                                output.push_str("                            taxable_base * rate\n");
                                                output.push_str("                        }\n");
                                            }
                                            // Wildcard fallback inside filing_status match for this age
                                            let (has_single, has_mfj) = match age_val {
                                                Value::Object(fsmap_check) => (fsmap_check.get("Single").is_some(), fsmap_check.get("MarriedFilingJointly").is_some()),
                                                _ => (false, false),
                                            };
                                            if has_single {
                                                output.push_str(&format!("                        _ => return get_taxable_social_security(state, {}, {}, &FilingStatus::Single, income, social_security_income),\n", y, a));
                                            } else if has_mfj {
                                                output.push_str(&format!("                        _ => return get_taxable_social_security(state, {}, {}, &FilingStatus::MarriedFilingJointly, income, social_security_income),\n", y, a));
                                            } else {
                                                output.push_str(&format!("                        _ => return social_security_income * federal_rate({}, &FilingStatus::Single, income),\n", y));
                                            }
                                            output.push_str("                    },\n");
                                        }
                                    }
                                    // Ensure exhaustiveness for the age match
                                    output.push_str(&format!("                    _ => social_security_income * federal_rate({}, filing_status, income),\n", y));
                                    output.push_str("                }\n");
                                } else {
                                    output.push_str("                0.0\n");
                                }
                            }
                        }
                        output.push_str("            }\n");
                    }
                }

                if let Some(latest) = latest_year {
                    output.push_str(&format!(
                        "            _ => {{ eprintln!(\"Year {{}} not supported for {}. Defaulting to latest ({}).\", year); return get_taxable_social_security(state, {}, age, filing_status, income, social_security_income); }}\n",
                        state_code.to_lowercase(), latest, latest
                    ));
                } else {
                    output.push_str("            _ => 0.0\n");
                }
            }
            output.push_str("        },\n");
        }
    }

    output.push_str("        _ => {\n");
    output.push_str("            eprintln!(\"Error: State '{}' is not currently supported for social security taxation.\", state);\n");
    output.push_str("            0.0\n");
    output.push_str("        }\n");

    output.push_str("    }\n}\n");

    fs::write(&generated_output_path, output)
        .map_err(|e| format!("Failed to write to {}: {}", generated_output_path.display(), e))?;
    eprintln!("DEBUG: Successfully wrote get_taxable_social_security implementation to: {:?}", generated_output_path.display());

    Ok(())
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let cargo_manifest_dir = env::var("CARGO_MANIFEST_DIR")?;
    let cargo_manifest_path = Path::new(&cargo_manifest_dir);

    println!("cargo:rerun-if-changed=build.rs"); 
    eprintln!("DEBUG: build.rs started.");

    generate_tax_brackets(cargo_manifest_path)?;
    generate_deductions(cargo_manifest_path)?;
    generate_get_tax_brackets (cargo_manifest_path)?;
    generate_get_deductions(cargo_manifest_path)?;
    generate_get_taxable_social_security(cargo_manifest_path)?;


    Ok(())
}