// This file is automatically generated by build.rs
// Do not edit this file directly. Changes will be overwritten.

use crate::FilingStatus;
use crate::Deduction;
use crate::income_based_deduction;

/// Provides standard deductions for a given state, year, and filing status.
/// This function is generated by build.rs.
pub fn get_deductions(state: &str, year: i32, filing_status: &FilingStatus, income: f64) -> Deduction {
    let state_lower = state.to_lowercase();
    match state_lower.as_str() {
        "ak" => match year {
            2024 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 0.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 0.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 0.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 0.0 },
                FilingStatus::Single => Deduction { standard_deduction: 0.0 },
            }
            _ => {
                eprintln!("Year {} not supported for {}. Defaulting to standard deduction for Single filing status.", year, state_lower);
                Deduction { standard_deduction: 0.0 }
            }
        },
        "al" => match year {
            2024 => income_based_deduction::al_standard_deduction_2024(income, filing_status),
            _ => {
                eprintln!("Year {} not supported for {}. Defaulting to latest ({}) deduction.", year, state_lower, 2024);
                income_based_deduction::al_standard_deduction_2024(income, filing_status)
            }
        },
        "ar" => match year {
            2024 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 2340.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 4680.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 2340.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 2340.0 },
                FilingStatus::Single => Deduction { standard_deduction: 2340.0 },
            }
            _ => {
                eprintln!("Year {} not supported for {}. Defaulting to standard deduction for Single filing status.", year, state_lower);
                Deduction { standard_deduction: 2340.0 }
            }
        },
        "az" => match year {
            2024 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 21900.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 29200.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 14600.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 29200.0 },
                FilingStatus::Single => Deduction { standard_deduction: 14600.0 },
            }
            _ => {
                eprintln!("Year {} not supported for {}. Defaulting to standard deduction for Single filing status.", year, state_lower);
                Deduction { standard_deduction: 14600.0 }
            }
        },
        "ca" => match year {
            2024 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 11080.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 11080.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 5540.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 11080.0 },
                FilingStatus::Single => Deduction { standard_deduction: 5540.0 },
            }
            _ => {
                eprintln!("Year {} not supported for {}. Defaulting to standard deduction for Single filing status.", year, state_lower);
                Deduction { standard_deduction: 5540.0 }
            }
        },
        "co" => match year {
            2024 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 0.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 0.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 0.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 0.0 },
                FilingStatus::Single => Deduction { standard_deduction: 0.0 },
            }
            _ => {
                eprintln!("Year {} not supported for {}. Defaulting to standard deduction for Single filing status.", year, state_lower);
                Deduction { standard_deduction: 0.0 }
            }
        },
        "ct" => match year {
            2024 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 0.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 0.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 0.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 0.0 },
                FilingStatus::Single => Deduction { standard_deduction: 0.0 },
            }
            _ => {
                eprintln!("Year {} not supported for {}. Defaulting to standard deduction for Single filing status.", year, state_lower);
                Deduction { standard_deduction: 0.0 }
            }
        },
        "de" => match year {
            2024 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 5700.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 11400.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 5700.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 5700.0 },
                FilingStatus::Single => Deduction { standard_deduction: 5700.0 },
            }
            _ => {
                eprintln!("Year {} not supported for {}. Defaulting to standard deduction for Single filing status.", year, state_lower);
                Deduction { standard_deduction: 5700.0 }
            }
        },
        "fl" => match year {
            2024 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 0.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 0.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 0.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 0.0 },
                FilingStatus::Single => Deduction { standard_deduction: 0.0 },
            }
            _ => {
                eprintln!("Year {} not supported for {}. Defaulting to standard deduction for Single filing status.", year, state_lower);
                Deduction { standard_deduction: 0.0 }
            }
        },
        "ga" => match year {
            2024 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 12000.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 24000.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 12000.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 12000.0 },
                FilingStatus::Single => Deduction { standard_deduction: 12000.0 },
            }
            _ => {
                eprintln!("Year {} not supported for {}. Defaulting to standard deduction for Single filing status.", year, state_lower);
                Deduction { standard_deduction: 12000.0 }
            }
        },
        "hi" => match year {
            2024 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 6424.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 8800.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 4400.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 8800.0 },
                FilingStatus::Single => Deduction { standard_deduction: 4400.0 },
            }
            2025 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 6424.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 8800.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 4400.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 8800.0 },
                FilingStatus::Single => Deduction { standard_deduction: 4400.0 },
            }
            _ => {
                eprintln!("Year {} not supported for {}. Defaulting to standard deduction for Single filing status.", year, state_lower);
                Deduction { standard_deduction: 4400.0 }
            }
        },
        "ia" => match year {
            2024 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 21900.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 29200.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 14600.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 29200.0 },
                FilingStatus::Single => Deduction { standard_deduction: 14600.0 },
            }
            2025 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 22500.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 30000.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 15000.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 30000.0 },
                FilingStatus::Single => Deduction { standard_deduction: 15000.0 },
            }
            _ => {
                eprintln!("Year {} not supported for {}. Defaulting to standard deduction for Single filing status.", year, state_lower);
                Deduction { standard_deduction: 15000.0 }
            }
        },
        "id" => match year {
            2024 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 21900.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 29200.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 14600.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 29200.0 },
                FilingStatus::Single => Deduction { standard_deduction: 14600.0 },
            }
            2025 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 22500.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 30000.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 15000.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 30000.0 },
                FilingStatus::Single => Deduction { standard_deduction: 15000.0 },
            }
            _ => {
                eprintln!("Year {} not supported for {}. Defaulting to standard deduction for Single filing status.", year, state_lower);
                Deduction { standard_deduction: 15000.0 }
            }
        },
        "il" => match year {
            2024 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 0.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 0.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 0.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 0.0 },
                FilingStatus::Single => Deduction { standard_deduction: 0.0 },
            }
            _ => {
                eprintln!("Year {} not supported for {}. Defaulting to standard deduction for Single filing status.", year, state_lower);
                Deduction { standard_deduction: 0.0 }
            }
        },
        "in" => match year {
            2024 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 0.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 0.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 0.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 0.0 },
                FilingStatus::Single => Deduction { standard_deduction: 0.0 },
            }
            _ => {
                eprintln!("Year {} not supported for {}. Defaulting to standard deduction for Single filing status.", year, state_lower);
                Deduction { standard_deduction: 0.0 }
            }
        },
        "ks" => match year {
            2024 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 6180.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 8240.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 4120.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 8240.0 },
                FilingStatus::Single => Deduction { standard_deduction: 3605.0 },
            }
            _ => {
                eprintln!("Year {} not supported for {}. Defaulting to standard deduction for Single filing status.", year, state_lower);
                Deduction { standard_deduction: 3605.0 }
            }
        },
        "ky" => match year {
            2024 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 3160.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 3160.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 3160.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 3160.0 },
                FilingStatus::Single => Deduction { standard_deduction: 3160.0 },
            }
            2025 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 3270.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 3270.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 3270.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 3270.0 },
                FilingStatus::Single => Deduction { standard_deduction: 3270.0 },
            }
            _ => {
                eprintln!("Year {} not supported for {}. Defaulting to standard deduction for Single filing status.", year, state_lower);
                Deduction { standard_deduction: 3270.0 }
            }
        },
        "la" => match year {
            2024 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 9000.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 9000.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 4500.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 9000.0 },
                FilingStatus::Single => Deduction { standard_deduction: 4500.0 },
            }
            2025 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 25000.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 25000.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 12500.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 25000.0 },
                FilingStatus::Single => Deduction { standard_deduction: 12500.0 },
            }
            _ => {
                eprintln!("Year {} not supported for {}. Defaulting to standard deduction for Single filing status.", year, state_lower);
                Deduction { standard_deduction: 12500.0 }
            }
        },
        "ma" => match year {
            2024 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 0.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 0.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 0.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 0.0 },
                FilingStatus::Single => Deduction { standard_deduction: 0.0 },
            }
            2025 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 0.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 0.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 0.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 0.0 },
                FilingStatus::Single => Deduction { standard_deduction: 0.0 },
            }
            _ => {
                eprintln!("Year {} not supported for {}. Defaulting to standard deduction for Single filing status.", year, state_lower);
                Deduction { standard_deduction: 0.0 }
            }
        },
        "md" => match year {
            2024 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 5450.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 5450.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 2700.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 5450.0 },
                FilingStatus::Single => Deduction { standard_deduction: 2700.0 },
            }
            _ => {
                eprintln!("Year {} not supported for {}. Defaulting to standard deduction for Single filing status.", year, state_lower);
                Deduction { standard_deduction: 2700.0 }
            }
        },
        "me" => match year {
            2024 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 21900.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 29200.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 14600.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 29200.0 },
                FilingStatus::Single => Deduction { standard_deduction: 14600.0 },
            }
            2025 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 22500.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 30000.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 15000.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 30000.0 },
                FilingStatus::Single => Deduction { standard_deduction: 15000.0 },
            }
            _ => {
                eprintln!("Year {} not supported for {}. Defaulting to standard deduction for Single filing status.", year, state_lower);
                Deduction { standard_deduction: 15000.0 }
            }
        },
        "mi" => match year {
            2024 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 0.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 0.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 0.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 0.0 },
                FilingStatus::Single => Deduction { standard_deduction: 0.0 },
            }
            2025 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 0.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 0.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 0.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 0.0 },
                FilingStatus::Single => Deduction { standard_deduction: 0.0 },
            }
            _ => {
                eprintln!("Year {} not supported for {}. Defaulting to standard deduction for Single filing status.", year, state_lower);
                Deduction { standard_deduction: 0.0 }
            }
        },
        "mn" => match year {
            2024 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 21900.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 29150.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 14575.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 29150.0 },
                FilingStatus::Single => Deduction { standard_deduction: 14575.0 },
            }
            2025 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 22500.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 29900.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 14950.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 29900.0 },
                FilingStatus::Single => Deduction { standard_deduction: 14950.0 },
            }
            _ => {
                eprintln!("Year {} not supported for {}. Defaulting to standard deduction for Single filing status.", year, state_lower);
                Deduction { standard_deduction: 14950.0 }
            }
        },
        "mo" => match year {
            2024 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 21900.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 29200.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 14600.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 29200.0 },
                FilingStatus::Single => Deduction { standard_deduction: 14600.0 },
            }
            _ => {
                eprintln!("Year {} not supported for {}. Defaulting to standard deduction for Single filing status.", year, state_lower);
                Deduction { standard_deduction: 14600.0 }
            }
        },
        "ms" => match year {
            2024 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 3400.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 4600.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 2300.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 4600.0 },
                FilingStatus::Single => Deduction { standard_deduction: 2300.0 },
            }
            2025 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 22500.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 29900.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 14950.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 29900.0 },
                FilingStatus::Single => Deduction { standard_deduction: 2300.0 },
            }
            _ => {
                eprintln!("Year {} not supported for {}. Defaulting to standard deduction for Single filing status.", year, state_lower);
                Deduction { standard_deduction: 2300.0 }
            }
        },
        "mt" => match year {
            2024 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 21900.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 29200.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 14600.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 29200.0 },
                FilingStatus::Single => Deduction { standard_deduction: 14600.0 },
            }
            2025 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 22500.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 30000.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 15000.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 30000.0 },
                FilingStatus::Single => Deduction { standard_deduction: 15000.0 },
            }
            _ => {
                eprintln!("Year {} not supported for {}. Defaulting to standard deduction for Single filing status.", year, state_lower);
                Deduction { standard_deduction: 15000.0 }
            }
        },
        "nc" => match year {
            2024 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 19125.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 25500.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 12750.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 25500.0 },
                FilingStatus::Single => Deduction { standard_deduction: 12750.0 },
            }
            2025 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 19125.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 25500.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 12750.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 25500.0 },
                FilingStatus::Single => Deduction { standard_deduction: 12750.0 },
            }
            _ => {
                eprintln!("Year {} not supported for {}. Defaulting to standard deduction for Single filing status.", year, state_lower);
                Deduction { standard_deduction: 12750.0 }
            }
        },
        "nd" => match year {
            2024 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 21900.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 29200.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 14600.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 29200.0 },
                FilingStatus::Single => Deduction { standard_deduction: 14600.0 },
            }
            2025 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 22500.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 30000.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 15000.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 30000.0 },
                FilingStatus::Single => Deduction { standard_deduction: 15000.0 },
            }
            _ => {
                eprintln!("Year {} not supported for {}. Defaulting to standard deduction for Single filing status.", year, state_lower);
                Deduction { standard_deduction: 15000.0 }
            }
        },
        "ne" => match year {
            2024 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 12250.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 16700.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 8350.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 16700.0 },
                FilingStatus::Single => Deduction { standard_deduction: 8350.0 },
            }
            _ => {
                eprintln!("Year {} not supported for {}. Defaulting to standard deduction for Single filing status.", year, state_lower);
                Deduction { standard_deduction: 8350.0 }
            }
        },
        "nh" => match year {
            2024 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 0.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 0.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 0.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 0.0 },
                FilingStatus::Single => Deduction { standard_deduction: 0.0 },
            }
            2025 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 0.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 0.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 0.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 0.0 },
                FilingStatus::Single => Deduction { standard_deduction: 0.0 },
            }
            _ => {
                eprintln!("Year {} not supported for {}. Defaulting to standard deduction for Single filing status.", year, state_lower);
                Deduction { standard_deduction: 0.0 }
            }
        },
        "nj" => match year {
            2024 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 0.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 0.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 0.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 0.0 },
                FilingStatus::Single => Deduction { standard_deduction: 0.0 },
            }
            2025 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 0.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 0.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 0.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 0.0 },
                FilingStatus::Single => Deduction { standard_deduction: 0.0 },
            }
            _ => {
                eprintln!("Year {} not supported for {}. Defaulting to standard deduction for Single filing status.", year, state_lower);
                Deduction { standard_deduction: 0.0 }
            }
        },
        "nm" => match year {
            2024 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 21900.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 29200.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 14600.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 29200.0 },
                FilingStatus::Single => Deduction { standard_deduction: 14600.0 },
            }
            2025 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 22500.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 30000.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 15000.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 30000.0 },
                FilingStatus::Single => Deduction { standard_deduction: 15000.0 },
            }
            _ => {
                eprintln!("Year {} not supported for {}. Defaulting to standard deduction for Single filing status.", year, state_lower);
                Deduction { standard_deduction: 15000.0 }
            }
        },
        "nv" => match year {
            2024 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 0.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 0.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 0.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 0.0 },
                FilingStatus::Single => Deduction { standard_deduction: 0.0 },
            }
            2025 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 0.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 0.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 0.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 0.0 },
                FilingStatus::Single => Deduction { standard_deduction: 0.0 },
            }
            _ => {
                eprintln!("Year {} not supported for {}. Defaulting to standard deduction for Single filing status.", year, state_lower);
                Deduction { standard_deduction: 0.0 }
            }
        },
        "ny" => match year {
            2024 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 11200.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 16050.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 8000.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 16050.0 },
                FilingStatus::Single => Deduction { standard_deduction: 8000.0 },
            }
            _ => {
                eprintln!("Year {} not supported for {}. Defaulting to standard deduction for Single filing status.", year, state_lower);
                Deduction { standard_deduction: 8000.0 }
            }
        },
        "oh" => match year {
            2024 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 0.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 0.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 0.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 0.0 },
                FilingStatus::Single => Deduction { standard_deduction: 0.0 },
            }
            2025 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 0.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 0.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 0.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 0.0 },
                FilingStatus::Single => Deduction { standard_deduction: 0.0 },
            }
            _ => {
                eprintln!("Year {} not supported for {}. Defaulting to standard deduction for Single filing status.", year, state_lower);
                Deduction { standard_deduction: 0.0 }
            }
        },
        "ok" => match year {
            2024 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 9350.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 12700.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 6350.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 12700.0 },
                FilingStatus::Single => Deduction { standard_deduction: 6350.0 },
            }
            _ => {
                eprintln!("Year {} not supported for {}. Defaulting to standard deduction for Single filing status.", year, state_lower);
                Deduction { standard_deduction: 6350.0 }
            }
        },
        "or" => match year {
            2024 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 4420.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 5495.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 2745.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 5495.0 },
                FilingStatus::Single => Deduction { standard_deduction: 2745.0 },
            }
            2025 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 4500.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 5670.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 2835.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 5670.0 },
                FilingStatus::Single => Deduction { standard_deduction: 2835.0 },
            }
            _ => {
                eprintln!("Year {} not supported for {}. Defaulting to standard deduction for Single filing status.", year, state_lower);
                Deduction { standard_deduction: 2835.0 }
            }
        },
        "pa" => match year {
            2024 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 0.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 0.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 0.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 0.0 },
                FilingStatus::Single => Deduction { standard_deduction: 0.0 },
            }
            2025 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 0.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 0.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 0.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 0.0 },
                FilingStatus::Single => Deduction { standard_deduction: 0.0 },
            }
            _ => {
                eprintln!("Year {} not supported for {}. Defaulting to standard deduction for Single filing status.", year, state_lower);
                Deduction { standard_deduction: 0.0 }
            }
        },
        "ri" => match year {
            2024 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 15850.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 21150.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 10550.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 21150.0 },
                FilingStatus::Single => Deduction { standard_deduction: 10550.0 },
            }
            2025 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 16350.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 21800.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 10900.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 21800.0 },
                FilingStatus::Single => Deduction { standard_deduction: 10900.0 },
            }
            _ => {
                eprintln!("Year {} not supported for {}. Defaulting to standard deduction for Single filing status.", year, state_lower);
                Deduction { standard_deduction: 10900.0 }
            }
        },
        "sc" => match year {
            2024 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 21900.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 29200.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 14600.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 29200.0 },
                FilingStatus::Single => Deduction { standard_deduction: 14600.0 },
            }
            2025 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 22500.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 30000.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 15000.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 30000.0 },
                FilingStatus::Single => Deduction { standard_deduction: 15000.0 },
            }
            _ => {
                eprintln!("Year {} not supported for {}. Defaulting to standard deduction for Single filing status.", year, state_lower);
                Deduction { standard_deduction: 15000.0 }
            }
        },
        "sd" => match year {
            2024 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 0.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 0.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 0.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 0.0 },
                FilingStatus::Single => Deduction { standard_deduction: 0.0 },
            }
            _ => {
                eprintln!("Year {} not supported for {}. Defaulting to standard deduction for Single filing status.", year, state_lower);
                Deduction { standard_deduction: 0.0 }
            }
        },
        "tn" => match year {
            2024 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 0.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 0.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 0.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 0.0 },
                FilingStatus::Single => Deduction { standard_deduction: 0.0 },
            }
            _ => {
                eprintln!("Year {} not supported for {}. Defaulting to standard deduction for Single filing status.", year, state_lower);
                Deduction { standard_deduction: 0.0 }
            }
        },
        "tx" => match year {
            2024 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 0.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 0.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 0.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 0.0 },
                FilingStatus::Single => Deduction { standard_deduction: 0.0 },
            }
            _ => {
                eprintln!("Year {} not supported for {}. Defaulting to standard deduction for Single filing status.", year, state_lower);
                Deduction { standard_deduction: 0.0 }
            }
        },
        "ut" => match year {
            2024 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 21900.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 29200.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 14600.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 29200.0 },
                FilingStatus::Single => Deduction { standard_deduction: 14600.0 },
            }
            2025 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 22500.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 30000.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 15000.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 30000.0 },
                FilingStatus::Single => Deduction { standard_deduction: 15000.0 },
            }
            _ => {
                eprintln!("Year {} not supported for {}. Defaulting to standard deduction for Single filing status.", year, state_lower);
                Deduction { standard_deduction: 15000.0 }
            }
        },
        "va" => match year {
            2024 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 8500.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 17000.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 8500.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 17000.0 },
                FilingStatus::Single => Deduction { standard_deduction: 8500.0 },
            }
            2025 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 8000.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 16000.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 8000.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 16000.0 },
                FilingStatus::Single => Deduction { standard_deduction: 8000.0 },
            }
            _ => {
                eprintln!("Year {} not supported for {}. Defaulting to standard deduction for Single filing status.", year, state_lower);
                Deduction { standard_deduction: 8000.0 }
            }
        },
        "vt" => match year {
            2024 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 11100.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 14850.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 7400.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 14850.0 },
                FilingStatus::Single => Deduction { standard_deduction: 7400.0 },
            }
            _ => {
                eprintln!("Year {} not supported for {}. Defaulting to standard deduction for Single filing status.", year, state_lower);
                Deduction { standard_deduction: 7400.0 }
            }
        },
        "wa" => match year {
            2024 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 21900.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 29200.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 14600.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 29200.0 },
                FilingStatus::Single => Deduction { standard_deduction: 14600.0 },
            }
            2025 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 22500.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 30000.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 15000.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 30000.0 },
                FilingStatus::Single => Deduction { standard_deduction: 15000.0 },
            }
            _ => {
                eprintln!("Year {} not supported for {}. Defaulting to standard deduction for Single filing status.", year, state_lower);
                Deduction { standard_deduction: 15000.0 }
            }
        },
        "wi" => match year {
            2024 => income_based_deduction::wi_standard_deduction_2024(income, filing_status),
            _ => {
                eprintln!("Year {} not supported for {}. Defaulting to latest ({}) deduction.", year, state_lower, 2024);
                income_based_deduction::wi_standard_deduction_2024(income, filing_status)
            }
        },
        "wv" => match year {
            2024 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 0.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 0.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 0.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 0.0 },
                FilingStatus::Single => Deduction { standard_deduction: 0.0 },
            }
            2025 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 0.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 0.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 0.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 0.0 },
                FilingStatus::Single => Deduction { standard_deduction: 0.0 },
            }
            _ => {
                eprintln!("Year {} not supported for {}. Defaulting to standard deduction for Single filing status.", year, state_lower);
                Deduction { standard_deduction: 0.0 }
            }
        },
        "wy" => match year {
            2024 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 0.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 0.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 0.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 0.0 },
                FilingStatus::Single => Deduction { standard_deduction: 0.0 },
            }
            2025 => match *filing_status {
                FilingStatus::HeadOfHousehold => Deduction { standard_deduction: 0.0 },
                FilingStatus::MarriedFilingJointly => Deduction { standard_deduction: 0.0 },
                FilingStatus::MarriedFilingSeparately => Deduction { standard_deduction: 0.0 },
                FilingStatus::QualifyingSurvivingSpouse => Deduction { standard_deduction: 0.0 },
                FilingStatus::Single => Deduction { standard_deduction: 0.0 },
            }
            _ => {
                eprintln!("Year {} not supported for {}. Defaulting to standard deduction for Single filing status.", year, state_lower);
                Deduction { standard_deduction: 0.0 }
            }
        },
        _ => {
            eprintln!("Error: State '{}' is not currently supported for deductions. Defaulting to 0 deduction.", state);
            Deduction { standard_deduction: 0.0 }
        }
    }
}
