// This file is automatically generated by build.rs
// Do not edit this file directly. Changes will be overwritten.

use crate::FilingStatus;

fn federal_rate(year: i32, filing_status: &FilingStatus, income: f64) -> f64 {
    match year {
        2024 => match filing_status {
            FilingStatus::MarriedFilingJointly => {
                let mut rate: f64 = 0.0;
                if income <= 34000.0 { rate = 0.0000; }
                else if income <= 44000.0 { rate = 0.5000; }
                else { rate = 0.8500; }
                rate
            }
            FilingStatus::Single => {
                let mut rate: f64 = 0.0;
                if income <= 25000.0 { rate = 0.0000; }
                else if income <= 34000.0 { rate = 0.5000; }
                else { rate = 0.8500; }
                rate
            }
            _ => {
                let mut rate: f64 = 0.0;
                if income <= 25000.0 { rate = 0.0000; }
                else if income <= 34000.0 { rate = 0.5000; }
                else { rate = 0.8500; }
                rate
            },
        },
        2025 => match filing_status {
            FilingStatus::MarriedFilingJointly => {
                let mut rate: f64 = 0.0;
                if income <= 34000.0 { rate = 0.0000; }
                else if income <= 44000.0 { rate = 0.5000; }
                else { rate = 0.8500; }
                rate
            }
            FilingStatus::Single => {
                let mut rate: f64 = 0.0;
                if income <= 25000.0 { rate = 0.0000; }
                else if income <= 34000.0 { rate = 0.5000; }
                else { rate = 0.8500; }
                rate
            }
            _ => {
                let mut rate: f64 = 0.0;
                if income <= 25000.0 { rate = 0.0000; }
                else if income <= 34000.0 { rate = 0.5000; }
                else { rate = 0.8500; }
                rate
            },
        },
        _ => { 0.85 }
    }
}

/// Returns the amount of Social Security income that is subject to tax for a given state/year.
pub fn get_taxable_social_security(state: &str, year: i32, age: i32, filing_status: &FilingStatus, income: f64, social_security_income: f64) -> f64 {
    let state_lower = state.to_lowercase();
    match state_lower.as_str() {
        "co" => match year {
            2024 => {
                let chosen_age = if age <= 64 { 64 } else {
                    if age <= 65 { 65 } else {
                        65 }  } ;
                match chosen_age {
                    64 => match filing_status {
                        FilingStatus::MarriedFilingJointly => {
                            let mut rate: f64 = 0.0;
                            let mut deduction: f64 = 0.0;
                            if income <= 25000.0 { rate = 0.0000; deduction = 0.0; }
                            else { rate = 0.5000; deduction = 20000.0; }
                            let taxable_base = (social_security_income - deduction).max(0.0);
                            taxable_base * rate
                        }
                        FilingStatus::Single => {
                            let mut rate: f64 = 0.0;
                            let mut deduction: f64 = 0.0;
                            if income <= 25000.0 { rate = 0.0000; deduction = 0.0; }
                            else { rate = 1.0000; deduction = 20000.0; }
                            let taxable_base = (social_security_income - deduction).max(0.0);
                            taxable_base * rate
                        }
                        _ => return get_taxable_social_security(state, 2024, 64, &FilingStatus::Single, income, social_security_income),
                    },
                    65 => match filing_status {
                        FilingStatus::MarriedFilingJointly => {
                            let mut rate: f64 = 0.0;
                            let mut deduction: f64 = 0.0;
                            rate = 0.0000; deduction = 0.0;
                            let taxable_base = (social_security_income - deduction).max(0.0);
                            taxable_base * rate
                        }
                        FilingStatus::Single => {
                            let mut rate: f64 = 0.0;
                            let mut deduction: f64 = 0.0;
                            rate = 0.0000; deduction = 0.0;
                            let taxable_base = (social_security_income - deduction).max(0.0);
                            taxable_base * rate
                        }
                        _ => return social_security_income * federal_rate(2024, &FilingStatus::Single, income),
                    },
                    _ => social_security_income * federal_rate(2024, filing_status, income),
                }
            }
            _ => { eprintln!("Year {} not supported for co. Defaulting to latest (2024).", year); return get_taxable_social_security(state, 2024, age, filing_status, income, social_security_income); }
        },
        "ct" => match year {
            2024 => {
                match filing_status {
                    FilingStatus::MarriedFilingJointly => {
                        let mut rate: f64 = 0.0;
                        let mut deduction: f64 = 0.0;
                        if income <= 100000.0 { rate = 0.0000; deduction = 0.0; }
                        else { rate = 0.2500; deduction = 0.0; }
                        let taxable_base = (social_security_income - deduction).max(0.0);
                        taxable_base * rate
                    }
                    FilingStatus::Single => {
                        let mut rate: f64 = 0.0;
                        let mut deduction: f64 = 0.0;
                        if income <= 75000.0 { rate = 0.0000; deduction = 0.0; }
                        else { rate = 0.2500; deduction = 0.0; }
                        let taxable_base = (social_security_income - deduction).max(0.0);
                        taxable_base * rate
                    }
                    _ => return get_taxable_social_security(state, 2024, age, &FilingStatus::Single, income, social_security_income),
                }
            }
            _ => { eprintln!("Year {} not supported for ct. Defaulting to latest (2024).", year); return get_taxable_social_security(state, 2024, age, filing_status, income, social_security_income); }
        },
        "mt" => match year {
            2024 => {
                match filing_status {
                    FilingStatus::MarriedFilingJointly => social_security_income * federal_rate(2024, filing_status, income),
                    FilingStatus::Single => social_security_income * federal_rate(2024, filing_status, income),
                    _ => return get_taxable_social_security(state, 2024, age, &FilingStatus::Single, income, social_security_income),
                }
            }
            2025 => {
                match filing_status {
                    FilingStatus::MarriedFilingJointly => social_security_income * federal_rate(2025, filing_status, income),
                    FilingStatus::Single => social_security_income * federal_rate(2025, filing_status, income),
                    _ => return get_taxable_social_security(state, 2025, age, &FilingStatus::Single, income, social_security_income),
                }
            }
            _ => { eprintln!("Year {} not supported for mt. Defaulting to latest (2025).", year); return get_taxable_social_security(state, 2025, age, filing_status, income, social_security_income); }
        },
        "nm" => match year {
            2024 => {
                match filing_status {
                    FilingStatus::MarriedFilingJointly => {
                        let mut rate: f64 = 0.0;
                        let mut deduction: f64 = 0.0;
                        if income <= 150000.0 { rate = 0.0000; deduction = 0.0; }
                        else { rate = 1.0000; deduction = 0.0; }
                        let taxable_base = (social_security_income - deduction).max(0.0);
                        taxable_base * rate
                    }
                    FilingStatus::Single => {
                        let mut rate: f64 = 0.0;
                        let mut deduction: f64 = 0.0;
                        if income <= 100000.0 { rate = 0.0000; deduction = 0.0; }
                        else { rate = 1.0000; deduction = 0.0; }
                        let taxable_base = (social_security_income - deduction).max(0.0);
                        taxable_base * rate
                    }
                    _ => return get_taxable_social_security(state, 2024, age, &FilingStatus::Single, income, social_security_income),
                }
            }
            _ => { eprintln!("Year {} not supported for nm. Defaulting to latest (2024).", year); return get_taxable_social_security(state, 2024, age, filing_status, income, social_security_income); }
        },
        "ri" => match year {
            2024 => {
                let chosen_age = if age <= 66 { 66 } else {
                    if age <= 67 { 67 } else {
                        67 }  } ;
                match chosen_age {
                    66 => match filing_status {
                        FilingStatus::MarriedFilingJointly => {
                            let mut rate: f64 = 0.0;
                            let mut deduction: f64 = 0.0;
                            rate = 1.0000; deduction = 0.0;
                            let taxable_base = (social_security_income - deduction).max(0.0);
                            taxable_base * rate
                        }
                        FilingStatus::Single => {
                            let mut rate: f64 = 0.0;
                            let mut deduction: f64 = 0.0;
                            rate = 1.0000; deduction = 0.0;
                            let taxable_base = (social_security_income - deduction).max(0.0);
                            taxable_base * rate
                        }
                        _ => return get_taxable_social_security(state, 2024, 66, &FilingStatus::Single, income, social_security_income),
                    },
                    67 => match filing_status {
                        FilingStatus::MarriedFilingJointly => {
                            let mut rate: f64 = 0.0;
                            let mut deduction: f64 = 0.0;
                            if income <= 130250.0 { rate = 0.0000; deduction = 0.0; }
                            else { rate = 1.0000; deduction = 0.0; }
                            let taxable_base = (social_security_income - deduction).max(0.0);
                            taxable_base * rate
                        }
                        FilingStatus::Single => {
                            let mut rate: f64 = 0.0;
                            let mut deduction: f64 = 0.0;
                            if income <= 104000.0 { rate = 0.0000; deduction = 0.0; }
                            else { rate = 1.0000; deduction = 0.0; }
                            let taxable_base = (social_security_income - deduction).max(0.0);
                            taxable_base * rate
                        }
                        _ => return get_taxable_social_security(state, 2024, 67, &FilingStatus::Single, income, social_security_income),
                    },
                    _ => social_security_income * federal_rate(2024, filing_status, income),
                }
            }
            _ => { eprintln!("Year {} not supported for ri. Defaulting to latest (2024).", year); return get_taxable_social_security(state, 2024, age, filing_status, income, social_security_income); }
        },
        "ut" => match year {
            2025 => {
                match filing_status {
                    FilingStatus::MarriedFilingJointly => {
                        let mut rate: f64 = 0.0;
                        let mut deduction: f64 = 0.0;
                        if income <= 90000.0 { rate = 0.0000; deduction = 0.0; }
                        else { rate = 1.0000; deduction = 0.0; }
                        let taxable_base = (social_security_income - deduction).max(0.0);
                        taxable_base * rate
                    }
                    FilingStatus::Single => {
                        let mut rate: f64 = 0.0;
                        let mut deduction: f64 = 0.0;
                        if income <= 54000.0 { rate = 0.0000; deduction = 0.0; }
                        else { rate = 1.0000; deduction = 0.0; }
                        let taxable_base = (social_security_income - deduction).max(0.0);
                        taxable_base * rate
                    }
                    _ => return get_taxable_social_security(state, 2025, age, &FilingStatus::Single, income, social_security_income),
                }
            }
            _ => { eprintln!("Year {} not supported for ut. Defaulting to latest (2025).", year); return get_taxable_social_security(state, 2025, age, filing_status, income, social_security_income); }
        },
        "vt" => match year {
            2025 => {
                match filing_status {
                    FilingStatus::MarriedFilingJointly => {
                        let mut rate: f64 = 0.0;
                        let mut deduction: f64 = 0.0;
                        if income <= 65000.0 { rate = 0.0000; deduction = 0.0; }
                        else { rate = 1.0000; deduction = 0.0; }
                        let taxable_base = (social_security_income - deduction).max(0.0);
                        taxable_base * rate
                    }
                    FilingStatus::Single => {
                        let mut rate: f64 = 0.0;
                        let mut deduction: f64 = 0.0;
                        if income <= 50000.0 { rate = 0.0000; deduction = 0.0; }
                        else { rate = 1.0000; deduction = 0.0; }
                        let taxable_base = (social_security_income - deduction).max(0.0);
                        taxable_base * rate
                    }
                    _ => return get_taxable_social_security(state, 2025, age, &FilingStatus::Single, income, social_security_income),
                }
            }
            _ => { eprintln!("Year {} not supported for vt. Defaulting to latest (2025).", year); return get_taxable_social_security(state, 2025, age, filing_status, income, social_security_income); }
        },
        _ => {
            eprintln!("Error: State '{}' is not currently supported for social security taxation.", state);
            0.0
        }
    }
}
